### PR TITLE
🚨 switch to patched simp_le fork from @zenhack

### PR DESCRIPTION
**Pull request by dotcypress**
Switch to patched `simp_le` fork from @zenhack

Related [issue/drama](https://github.com/kuba/simp_le/issues/118)

### CODE REVIEW

**Comment by kudos** [comment]
For those who need to fix expired certs right away, I've forked @dotcypress's fork and turned it into an automated Docker Hub build https://hub.docker.com/r/kudoz/letsencrypt-simp_le.

Run `sed -i 's/dokkupaas/kudoz/g' /var/lib/dokku/plugins/enabled/letsencrypt/functions` to enable it and update your certs. Run `sed -i 's/kudoz/dokkupaas/g' /var/lib/dokku/plugins/enabled/letsencrypt/functions` and swap it back again afterwards.

**Comment by josegonzalez** [comment]
@sseemayer can you go in and just make it so we use our own build instead of relying on someone elses? I don't think switching to yet another fork is a good idea.

**Comment by joshmanders** [comment]
@kudos I'm getting an error on your image too.

```
$ dokku letsencrypt stackforge
=====> Let's Encrypt stackforge
-----> Updating letsencrypt docker image...
latest: Pulling from kudoz/letsencrypt-simp_le

Digest: sha256:dd69ae5afe57463b449595aa7c3595ae0d79a65f11c7da848b90878c8444c0af
Status: Image is up to date for kudoz/letsencrypt-simp_le:latest
       done updating
-----> Enabling ACME proxy for stackforge...
-----> Getting letsencrypt certificate for stackforge...
        - Domain 'stackforge.co'
        - Domain 'www.stackforge.co'
darkhttpd/1.11, copyright (c) 2003-2015 Emil Mikulic.
listening on: http://0.0.0.0:80/
2016-12-11 04:30:14,014:INFO:__main__:1211: Generating new account key
2016-12-11 04:30:14,772:INFO:requests.packages.urllib3.connectionpool:758: Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
Traceback (most recent call last):
  File "/simp_le-master/simp_le.py", line 1401, in main
    return main_with_exceptions(cli_args)
  File "/simp_le-master/simp_le.py", line 1386, in main_with_exceptions
    persist_new_data(args, existing_data)
  File "/simp_le-master/simp_le.py", line 1282, in persist_new_data
    client = registered_client(args, existing_data.account_key)
  File "/simp_le-master/simp_le.py", line 1224, in registered_client
    client = acme_client.Client(directory=args.server, key=key, net=net)
  File "/usr/lib/python2.7/site-packages/acme/client.py", line 63, in __init__
    self.net.get(directory).json())
  File "/usr/lib/python2.7/site-packages/acme/messages.py", line 169, in from_json
    raise jose.DeserializationError(str(error))
DeserializationError: Deserialization error: Wrong directory fields

Unhandled error has happened, traceback is above

Debugging tips: -v improves output verbosity. Help is available under --help.
-----> Certificate retrieval failed!
-----> Disabling ACME proxy for stackforge...
       done
```

**Comment by longhotsummer** [comment]
@kudos I'm also getting the same error again

```
latest: Pulling from kudoz/letsencrypt-simp_le
3690ec4760f9: Pull complete
c77e322d94fa: Pull complete
1a44127d38f2: Pull complete
Digest: sha256:dd69ae5afe57463b449595aa7c3595ae0d79a65f11c7da848b90878c8444c0af
Status: Downloaded newer image for kudoz/letsencrypt-simp_le:latest
       done updating
-----> Enabling ACME proxy for wazimap-za...
-----> Getting letsencrypt certificate for wazimap-za...
        - Domain 'wazimap.co.za'
        - Domain 'embed.wazimap.co.za'
        - Domain 'www.wazimap.co.za'
darkhttpd/1.11, copyright (c) 2003-2015 Emil Mikulic.
listening on: http://0.0.0.0:80/
2016-12-12 10:05:41,290:INFO:__main__:1211: Generating new account key
2016-12-12 10:05:42,554:INFO:requests.packages.urllib3.connectionpool:758: Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
Traceback (most recent call last):
  File "/simp_le-master/simp_le.py", line 1401, in main
    return main_with_exceptions(cli_args)
  File "/simp_le-master/simp_le.py", line 1386, in main_with_exceptions
    persist_new_data(args, existing_data)
  File "/simp_le-master/simp_le.py", line 1282, in persist_new_data
    client = registered_client(args, existing_data.account_key)
  File "/simp_le-master/simp_le.py", line 1224, in registered_client
    client = acme_client.Client(directory=args.server, key=key, net=net)
  File "/usr/lib/python2.7/site-packages/acme/client.py", line 63, in __init__
    self.net.get(directory).json())
  File "/usr/lib/python2.7/site-packages/acme/messages.py", line 169, in from_json
    raise jose.DeserializationError(str(error))
DeserializationError: Deserialization error: Wrong directory fields

Unhandled error has happened, traceback is above

Debugging tips: -v improves output verbosity. Help is available under --help.
-----> Certificate retrieval failed!
-----> Disabling ACME proxy for wazimap-za...
       done
```

**Comment by zenhack** [comment]
What version of acme is installed? The "fix" just raised the upper bound on the version constraint, so if somehow you didn't actually end up upgrading the package...

I probably need to change the lower bound as well.

**Comment by joshmanders** [comment]
I've upgraded acme to 0.9.3 and it still is giving that error. So I don't think the acme client being updated is causing this.

**Comment by joshmanders** [comment]
I have managed to fix this, soon it'll be available as part of an upgrade on the dokku plugin.

**Comment by dotcypress** [comment]
Closing in favor of https://github.com/dokku/docker-letsencrypt-simp_le/pull/2

**Pull request closed without merging**
